language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements.txt
    - pip install --upgrade coverage coveralls nose
script: 
    - printenv PWD
    - pip install .
    - nosetests --with-doctest --with-coverage --cover-package=gefura
after_success:
    coveralls
